name: workflow-2
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Getting code
        uses: actions/checkout@v4

      - name: Running Tests
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Installing dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Getting code
        uses: actions/checkout@v4

      - name: Running Tests
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Installing dependencies
        run: npm ci
      
      - name: Build Project
        run: npm run build
      
      - name: Deploying Project
        run: echo "Deployed!"
          
